name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build web app
      run: npm run build
      
    - name: Sync Capacitor
      run: npx cap sync android
      
    - name: Fix Gradle Wrapper
      run: |
        rm -rf android/gradlew android/gradlew-script
        mv android/gradlew.sh android/gradlew
        curl -L -o android/gradle/wrapper/gradle-wrapper.jar https://raw.githubusercontent.com/gradle/gradle/v8.5.0/gradle/wrapper/gradle-wrapper.jar
        chmod +x android/gradlew
        
    - name: Build Android Debug APK
      working-directory: ./android
      run: ./gradlew assembleDebug --no-daemon --stacktrace
      
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: moviebase-debug-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
        
    - name: Build Android Release APK
      working-directory: ./android
      run: ./gradlew assembleRelease --no-daemon --stacktrace
      continue-on-error: true
      
    - name: Upload Release APK (unsigned)
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: moviebase-release-apk
        path: android/app/build/outputs/apk/release/app-release-unsigned.apk
        retention-days: 30